/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from ".//geonetwork-openapi/service/customstyle-api";
export * from ".//geonetwork-openapi/service/formatters-api";
export * from ".//geonetwork-openapi/service/groups-api";
export * from ".//geonetwork-openapi/service/harvesters-api";
export * from ".//geonetwork-openapi/service/identifiers-api";
export * from ".//geonetwork-openapi/service/languages-api";
export * from ".//geonetwork-openapi/service/links-api";
export * from ".//geonetwork-openapi/service/logos-api";
export * from ".//geonetwork-openapi/service/mapservers-api";
export * from ".//geonetwork-openapi/service/me-api";
export * from ".//geonetwork-openapi/service/operations-api";
export * from ".//geonetwork-openapi/service/pages-api";
export * from ".//geonetwork-openapi/service/processes-api";
export * from ".//geonetwork-openapi/service/records-api";
export * from ".//geonetwork-openapi/service/regions-api";
export * from ".//geonetwork-openapi/service/registries-api";
export * from ".//geonetwork-openapi/service/related-api";
export * from ".//geonetwork-openapi/service/search-api";
export * from ".//geonetwork-openapi/service/selections-api";
export * from ".//geonetwork-openapi/service/site-api";
export * from ".//geonetwork-openapi/service/sources-api";
export * from ".//geonetwork-openapi/service/standards-api";
export * from ".//geonetwork-openapi/service/status-api";
export * from ".//geonetwork-openapi/service/tags-api";
export * from ".//geonetwork-openapi/service/tools-api";
export * from ".//geonetwork-openapi/service/ui-api";
export * from ".//geonetwork-openapi/service/userfeedback-api";
export * from ".//geonetwork-openapi/service/users-api";
export * from ".//geonetwork-openapi/service/usersearches-api";
export * from ".//geonetwork-openapi/service/userselections-api";
