/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Values } from "./values";

/**
 *
 * @export
 * @interface Element
 */
export interface Element {
  /**
   *
   * @type {string}
   * @memberof Element
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Element
   */
  definition?: string;
  /**
   *
   * @type {string}
   * @memberof Element
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof Element
   */
  link?: string;
  /**
   *
   * @type {string}
   * @memberof Element
   */
  type?: string;
  /**
   *
   * @type {Array<Values>}
   * @memberof Element
   */
  values?: Array<Values>;
}
