/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExtentDto
 */
export interface ExtentDto {
  /**
   *
   * @type {string}
   * @memberof ExtentDto
   */
  href?: string;
  /**
   *
   * @type {string}
   * @memberof ExtentDto
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof ExtentDto
   */
  xpath?: string;
  /**
   *
   * @type {string}
   * @memberof ExtentDto
   */
  description?: string;
}
