/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Description } from "./description";
import { FeatureType } from "./feature-type";
import { MultilingualValue } from "./multilingual-value";

/**
 *
 * @export
 * @interface FCRelatedMetadataItem
 */
export interface FCRelatedMetadataItem {
  /**
   *
   * @type {string}
   * @memberof FCRelatedMetadataItem
   */
  id?: string;
  /**
   *
   * @type {MultilingualValue}
   * @memberof FCRelatedMetadataItem
   */
  url?: MultilingualValue;
  /**
   *
   * @type {string}
   * @memberof FCRelatedMetadataItem
   */
  type?: string;
  /**
   *
   * @type {MultilingualValue}
   * @memberof FCRelatedMetadataItem
   */
  title: MultilingualValue;
  /**
   *
   * @type {Description}
   * @memberof FCRelatedMetadataItem
   */
  description: Description;
  /**
   *
   * @type {Array<string>}
   * @memberof FCRelatedMetadataItem
   */
  mdType: Array<string>;
  /**
   *
   * @type {string}
   * @memberof FCRelatedMetadataItem
   */
  origin?: string;
  /**
   *
   * @type {FeatureType}
   * @memberof FCRelatedMetadataItem
   */
  featureType: FeatureType;
}
