/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Field
 */
export interface Field {
  /**
   *
   * @type {string}
   * @memberof Field
   */
  template?: string;
  /**
   *
   * @type {string}
   * @memberof Field
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Field
   */
  xpath?: string;
  /**
   *
   * @type {string}
   * @memberof Field
   */
  indexField?: string;
  /**
   *
   * @type {string}
   * @memberof Field
   */
  use?: string;
  /**
   *
   * @type {boolean}
   * @memberof Field
   */
  removable?: boolean;
  /**
   *
   * @type {string}
   * @memberof Field
   */
  insertMode?: string;
  /**
   *
   * @type {string}
   * @memberof Field
   */
  codelist?: string;
}
