/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IProcessingReport
 */
export interface IProcessingReport {
  /**
   *
   * @type {string}
   * @memberof IProcessingReport
   */
  startIsoDateTime?: string;
  /**
   *
   * @type {string}
   * @memberof IProcessingReport
   */
  endIsoDateTime?: string;
  /**
   *
   * @type {number}
   * @memberof IProcessingReport
   */
  ellapsedTimeInSeconds?: number;
  /**
   *
   * @type {number}
   * @memberof IProcessingReport
   */
  totalTimeInSeconds?: number;
  /**
   *
   * @type {boolean}
   * @memberof IProcessingReport
   */
  running?: boolean;
  /**
   *
   * @type {string}
   * @memberof IProcessingReport
   */
  uuid?: string;
  /**
   *
   * @type {string}
   * @memberof IProcessingReport
   */
  type?: string;
}
