/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ISODate
 */
export interface ISODate {
  /**
   *
   * @type {string}
   * @memberof ISODate
   */
  internalDateTime?: string;
  /**
   *
   * @type {string}
   * @memberof ISODate
   */
  dateAndTime?: string;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  months?: number;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  hours?: number;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  minutes?: number;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  seconds?: number;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  days?: number;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  years?: number;
  /**
   *
   * @type {string}
   * @memberof ISODate
   */
  dateAsString?: string;
  /**
   *
   * @type {number}
   * @memberof ISODate
   */
  timeInSeconds?: number;
  /**
   *
   * @type {boolean}
   * @memberof ISODate
   */
  dateOnly?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ISODate
   */
  dateYearOnly?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ISODate
   */
  dateYearMonthOnly?: boolean;
  /**
   *
   * @type {string}
   * @memberof ISODate
   */
  timeAsString?: string;
  /**
   *
   * @type {string}
   * @memberof ISODate
   */
  dateAndTimeUtc?: string;
}
