/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ISODate } from "./isodate";

/**
 *
 * @export
 * @interface LinkStatus
 */
export interface LinkStatus {
  /**
   *
   * @type {number}
   * @memberof LinkStatus
   */
  id?: number;
  /**
   *
   * @type {ISODate}
   * @memberof LinkStatus
   */
  checkDate?: ISODate;
  /**
   *
   * @type {string}
   * @memberof LinkStatus
   */
  statusValue?: string;
  /**
   *
   * @type {string}
   * @memberof LinkStatus
   */
  statusInfo?: string;
  /**
   *
   * @type {string}
   * @memberof LinkStatus
   */
  batchKey?: string;
  /**
   *
   * @type {boolean}
   * @memberof LinkStatus
   */
  failing?: boolean;
}
