/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ISODate } from "./isodate";
import { LinkStatus } from "./link-status";
import { MetadataLink } from "./metadata-link";

/**
 *
 * @export
 * @interface Link
 */
export interface Link {
  /**
   *
   * @type {Set<MetadataLink>}
   * @memberof Link
   */
  records?: Set<MetadataLink>;
  /**
   *
   * @type {Set<LinkStatus>}
   * @memberof Link
   */
  linkStatus?: Set<LinkStatus>;
  /**
   *
   * @type {number}
   * @memberof Link
   */
  lastState?: number;
  /**
   *
   * @type {ISODate}
   * @memberof Link
   */
  lastCheck?: ISODate;
  /**
   *
   * @type {string}
   * @memberof Link
   */
  linkType?: LinkLinkTypeEnum;
  /**
   *
   * @type {number}
   * @memberof Link
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Link
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof Link
   */
  protocol?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum LinkLinkTypeEnum {
  Http = "HTTP",
  Metadata = "METADATA",
}
