/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MeResponse
 */
export interface MeResponse {
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  profile?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  surname?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  hash?: string;
  /**
   *
   * @type {string}
   * @memberof MeResponse
   */
  organisation?: string;
  /**
   *
   * @type {boolean}
   * @memberof MeResponse
   */
  admin?: boolean;
  /**
   *
   * @type {Array<number>}
   * @memberof MeResponse
   */
  groupsWithRegisteredUser?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof MeResponse
   */
  groupsWithEditor?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof MeResponse
   */
  groupsWithReviewer?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof MeResponse
   */
  groupsWithUserAdmin?: Array<number>;
}
