/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InfoReport } from "./info-report";
import { Report } from "./report";

/**
 *
 * @export
 * @interface MetadataProcessingReport
 */
export interface MetadataProcessingReport {
  /**
   *
   * @type {Array<Report>}
   * @memberof MetadataProcessingReport
   */
  errors?: Array<Report>;
  /**
   *
   * @type {Array<InfoReport>}
   * @memberof MetadataProcessingReport
   */
  infos?: Array<InfoReport>;
  /**
   *
   * @type {string}
   * @memberof MetadataProcessingReport
   */
  uuid?: string;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  totalRecords?: number;
  /**
   *
   * @type {Set<number>}
   * @memberof MetadataProcessingReport
   */
  metadata?: Set<number>;
  /**
   *
   * @type {{ [key: string]: Array<Report>; }}
   * @memberof MetadataProcessingReport
   */
  metadataErrors?: { [key: string]: Array<Report> };
  /**
   *
   * @type {{ [key: string]: Array<InfoReport>; }}
   * @memberof MetadataProcessingReport
   */
  metadataInfos?: { [key: string]: Array<InfoReport> };
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  numberOfRecords?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  numberOfRecordNotFound?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  numberOfRecordsNotEditable?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  numberOfNullRecords?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  numberOfRecordsProcessed?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  numberOfRecordsWithErrors?: number;
  /**
   *
   * @type {string}
   * @memberof MetadataProcessingReport
   */
  startIsoDateTime?: string;
  /**
   *
   * @type {string}
   * @memberof MetadataProcessingReport
   */
  endIsoDateTime?: string;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  ellapsedTimeInSeconds?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataProcessingReport
   */
  totalTimeInSeconds?: number;
  /**
   *
   * @type {boolean}
   * @memberof MetadataProcessingReport
   */
  running?: boolean;
  /**
   *
   * @type {string}
   * @memberof MetadataProcessingReport
   */
  type?: string;
}
