/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Identifier template details
 * @export
 * @interface MetadataIdentifierTemplate
 */
export interface MetadataIdentifierTemplate {
  /**
   *
   * @type {number}
   * @memberof MetadataIdentifierTemplate
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifierTemplate
   */
  template?: string;
  /**
   *
   * @type {boolean}
   * @memberof MetadataIdentifierTemplate
   */
  systemDefault?: boolean;
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifierTemplate
   */
  systemProvided_JPAWorkaround?: string;
  /**
   *
   * @type {boolean}
   * @memberof MetadataIdentifierTemplate
   */
  systemProvided?: boolean;
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifierTemplate
   */
  name?: string;
}
