/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Operation
 */
export interface Operation {
  /**
   *
   * @type {number}
   * @memberof Operation
   */
  id?: number;
  /**
   *
   * @type {boolean}
   * @memberof Operation
   */
  reserved?: boolean;
  /**
   *
   * @type {string}
   * @memberof Operation
   */
  reservedOperation?: OperationReservedOperationEnum;
  /**
   *
   * @type {string}
   * @memberof Operation
   */
  name?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof Operation
   */
  label?: { [key: string]: string };
}

/**
 * @export
 * @enum {string}
 */
export enum OperationReservedOperationEnum {
  View = "view",
  Download = "download",
  Editing = "editing",
  Notify = "notify",
  Dynamic = "dynamic",
  Featured = "featured",
}
