/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from "./link";
import { Pageable } from "./pageable";
import { Sort } from "./sort";

/**
 *
 * @export
 * @interface PageLink
 */
export interface PageLink {
  /**
   *
   * @type {number}
   * @memberof PageLink
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof PageLink
   */
  totalElements?: number;
  /**
   *
   * @type {number}
   * @memberof PageLink
   */
  numberOfElements?: number;
  /**
   *
   * @type {Pageable}
   * @memberof PageLink
   */
  pageable?: Pageable;
  /**
   *
   * @type {Sort}
   * @memberof PageLink
   */
  sort?: Sort;
  /**
   *
   * @type {boolean}
   * @memberof PageLink
   */
  last?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PageLink
   */
  first?: boolean;
  /**
   *
   * @type {number}
   * @memberof PageLink
   */
  size?: number;
  /**
   *
   * @type {Array<Link>}
   * @memberof PageLink
   */
  content?: Array<Link>;
  /**
   *
   * @type {number}
   * @memberof PageLink
   */
  number?: number;
  /**
   *
   * @type {boolean}
   * @memberof PageLink
   */
  empty?: boolean;
}
