/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RatingAverage
 */
export interface RatingAverage {
  /**
   *
   * @type {number}
   * @memberof RatingAverage
   */
  ratingCount?: number;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof RatingAverage
   */
  ratingAverages?: { [key: string]: number };
  /**
   *
   * @type {number}
   * @memberof RatingAverage
   */
  userfeedbackCount?: number;
  /**
   *
   * @type {string}
   * @memberof RatingAverage
   */
  lastComment?: string;
}
