/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegionResponse
 */
export interface RegionResponse {
  /**
   *
   * @type {number}
   * @memberof RegionResponse
   */
  north?: number;
  /**
   *
   * @type {number}
   * @memberof RegionResponse
   */
  east?: number;
  /**
   *
   * @type {number}
   * @memberof RegionResponse
   */
  south?: number;
  /**
   *
   * @type {number}
   * @memberof RegionResponse
   */
  west?: number;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof RegionResponse
   */
  label?: { [key: string]: string };
  /**
   *
   * @type {boolean}
   * @memberof RegionResponse
   */
  hasGeom?: boolean;
  /**
   *
   * @type {string}
   * @memberof RegionResponse
   */
  categoryId?: string;
  /**
   *
   * @type {string}
   * @memberof RegionResponse
   */
  id?: string;
}
