/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Report
 */
export interface Report {
  /**
   *
   * @type {string}
   * @memberof Report
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof Report
   */
  uuid?: string;
  /**
   *
   * @type {boolean}
   * @memberof Report
   */
  draft?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Report
   */
  approved?: boolean;
  /**
   *
   * @type {string}
   * @memberof Report
   */
  date?: string;
}
