/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Setting
 */
export interface Setting {
  /**
   *
   * @type {string}
   * @memberof Setting
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Setting
   */
  storedValue?: string;
  /**
   *
   * @type {string}
   * @memberof Setting
   */
  value?: string;
  /**
   *
   * @type {string}
   * @memberof Setting
   */
  dataType?: SettingDataTypeEnum;
  /**
   *
   * @type {number}
   * @memberof Setting
   */
  position?: number;
  /**
   *
   * @type {boolean}
   * @memberof Setting
   */
  internal?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Setting
   */
  encrypted?: boolean;
  /**
   *
   * @type {string}
   * @memberof Setting
   */
  encrypted_JpaWorkaround?: string;
  /**
   *
   * @type {string}
   * @memberof Setting
   */
  internal_JpaWorkaround?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum SettingDataTypeEnum {
  String = "STRING",
  Int = "INT",
  Boolean = "BOOLEAN",
  Json = "JSON",
}
