/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SystemInfo
 */
export interface SystemInfo {
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  stagingProfile?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  buildDate?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  version?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  subVersion?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  buildOsInfo?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  buildJavaVersion?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  buildJavaVendor?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  scmUrl?: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfo
   */
  scmRevision?: string;
  /**
   *
   * @type {boolean}
   * @memberof SystemInfo
   */
  devMode?: boolean;
}
