/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Translations
 */
export interface Translations {
  /**
   *
   * @type {string}
   * @memberof Translations
   */
  fieldName?: string;
  /**
   *
   * @type {number}
   * @memberof Translations
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Translations
   */
  langId?: string;
  /**
   *
   * @type {string}
   * @memberof Translations
   */
  value?: string;
}
