/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from "./address";
import { GrantedAuthority } from "./granted-authority";
import { UserSecurity } from "./user-security";

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  profile?: UserProfileEnum;
  /**
   *
   * @type {string}
   * @memberof User
   */
  surname?: string;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  enabled?: boolean;
  /**
   *
   * @type {number}
   * @memberof User
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  kind?: string;
  /**
   *
   * @type {Set<string>}
   * @memberof User
   */
  emailAddresses?: Set<string>;
  /**
   *
   * @type {Set<Address>}
   * @memberof User
   */
  addresses?: Set<Address>;
  /**
   *
   * @type {Address}
   * @memberof User
   */
  primaryAddress?: Address;
  /**
   *
   * @type {string}
   * @memberof User
   */
  organisation?: string;
  /**
   *
   * @type {UserSecurity}
   * @memberof User
   */
  security?: UserSecurity;
  /**
   *
   * @type {string}
   * @memberof User
   */
  lastLoginDate?: string;
  /**
   *
   * @type {Array<GrantedAuthority>}
   * @memberof User
   */
  authorities?: Array<GrantedAuthority>;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  accountNonExpired?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  accountNonLocked?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  credentialsNonExpired?: boolean;
  /**
   *
   * @type {string}
   * @memberof User
   */
  name?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum UserProfileEnum {
  Administrator = "Administrator",
  UserAdmin = "UserAdmin",
  Reviewer = "Reviewer",
  Editor = "Editor",
  RegisteredUser = "RegisteredUser",
  Guest = "Guest",
  Monitor = "Monitor",
}
