/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from "./address";

/**
 * User details
 * @export
 * @interface UserRegisterDto
 */
export interface UserRegisterDto {
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  profile?: string;
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  surname?: string;
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  organisation?: string;
  /**
   *
   * @type {Address}
   * @memberof UserRegisterDto
   */
  address?: Address;
  /**
   *
   * @type {string}
   * @memberof UserRegisterDto
   */
  captcha?: string;
}
