/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * User search details
 * @export
 * @interface UserSearchDto
 */
export interface UserSearchDto {
  /**
   *
   * @type {number}
   * @memberof UserSearchDto
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  featuredType?: string;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  creationDate?: string;
  /**
   *
   * @type {number}
   * @memberof UserSearchDto
   */
  creatorId?: number;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  creator?: string;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  logo?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof UserSearchDto
   */
  names?: { [key: string]: string };
  /**
   *
   * @type {Array<number>}
   * @memberof UserSearchDto
   */
  groups?: Array<number>;
}
