/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.0.6 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.6
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from "./address";

/**
 *
 * @export
 * @interface UserDto
 */
export interface UserDto {
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  profile?: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  surname?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserDto
   */
  emailAddresses?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  organisation?: string;
  /**
   *
   * @type {Array<Address>}
   * @memberof UserDto
   */
  addresses?: Array<Address>;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  kind?: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  password?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserDto
   */
  groupsRegisteredUser?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof UserDto
   */
  groupsEditor?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof UserDto
   */
  groupsReviewer?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof UserDto
   */
  groupsUserAdmin?: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof UserDto
   */
  enabled?: boolean;
  /**
   *
   * @type {UserDto}
   * @memberof UserDto
   */
  email?: UserDto;
}
